FROM ubuntu:18.04

COPY sources-18.04-azure.list /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    default-jdk \
    cmake \
    build-essential \
    python3-setuptools \
    python3-wheel \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*
