name: Java CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-18.04, windows-2016]

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle on Windows
      if: startsWith(runner.os, 'Windows')
      run: ./gradlew build

    - name: Build with Gradle on Linux
      if: startsWith(runner.os, 'Linux')
      run: sudo chmod +x gradlew && ./gradlew build
