name: CI

on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle on Windows
      if: startsWith(runner.os, 'Windows')
      run: ./gradlew buildNative build --info

    - name: Build with Gradle on Linux
      if: startsWith(runner.os, 'Linux')
      run: sudo chmod +x gradlew && ./gradlew buildNative build --info
