name: CI

on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest]
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Build natives on Windows
      if: startsWith(runner.os, 'Windows')
      run: |
        pip install conan
        conan remote add conan-center "https://conan.bintray.com" --f
        conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan" --f
        conan user -p "Open Simulation Platform" -r osp osp
        cd cse-core4j-native
        conan install . -s build_type=Release --install-folder=cmake-build-release --build=missing
        cd cmake-build-release
        cmake .. -DCMAKE_BUILD_TYPE=Release -A x64
        cmake --build . --config Release
      shell: bash

    - name: Build natives on Linux
      if: startsWith(runner.os, 'Linux')
      run: |
        sudo pip install conan
        conan remote add conan-center "https://conan.bintray.com" --f
        conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan" --f
        conan user -p "Open Simulation Platform" -r osp osp
        cd cse-core4j-native
        conan install . -s build_type=Release -s compiler.libcxx=libstdc++11 --install-folder=cmake-build-release --build=missing
        cd cmake-build-release
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
      shell: bash

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle on Windows
      if: startsWith(runner.os, 'Windows')
      run: ./gradlew build --info

    - name: Build with Gradle on Linux
      if: startsWith(runner.os, 'Linux')
      run: sudo chmod +x gradlew && ./gradlew build --info
